find_path(MSDFGEN_INCLUDE_DIR NAMES msdfgen/msdfgen.h PATHS ${CONAN_INCLUDE_DIRS_MSDFGEN})
find_library(MSDFGEN_LIBRARY NAMES ${CONAN_LIBS_MSDFGEN} PATHS ${CONAN_LIB_DIRS_MSDFGEN})

set(MSDFGEN_FOUND TRUE)
set(MSDFGEN_INCLUDE_DIRS ${MSDFGEN_INCLUDE_DIR})
set(MSDFGEN_LIBRARIES ${MSDFGEN_LIBRARY})
mark_as_advanced(MSDFGEN_LIBRARY MSDFGEN_INCLUDE_DIR)
