name: Deploy Library (Auto)

on:
  push:
    branches: 'main'
    paths: 'recipe/*'

jobs:
  select-recipes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths: ${{ github. }}
    steps:
      - id: 'path-cleanup'
        uses: iceshard-engine/.github/.github/actions/conan2-conandata-versions@main
        with:
          conandata-path: ''
