name: Deploy All (manual)
run-name: Deploy All (${{ inputs.category }})

on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Deployment of tools or libraries for the given user and channel'
        required: true
        type: choice
        options:
        - 'Tools'
        - 'Libraries'
      platform:
        description: 'The platform that the library should be deployed for.'
        required: true
        type: choice
        default: 'all'
        options:
        - windows
        - linux

jobs:
  deploy-basic-tools:
    name: Deploy Basic Tools
    if: ${{ inputs.category == 'Tools' }}
    strategy:
      matrix:
        include:
          - tool: 'fastbuild-installer'
            version: '1.12'
          - tool: 'fastbuild-generator'
            version: '0.4.2'
          - tool: 'premake-installer'
            version: '5.0.0'
          - tool: 'premake-generator'
            version: '0.2.0'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Deploy (${{ matrix.tool }}/${{ matrix.version }})
        uses: ./.github/workflows/deploy_tool.yml
        with:
          tool: ${{ matrix.tool }}
          version: ${{ matrix.version }}
          user: iceshard
          channel: stable
          platform: ${{ inputs.platform }}

  deploy-conan-iceshard-tools:
    name: Deploy (conan-iceshard-tools, 1.0.0)
    needs: deploy-basic-tools
    runs-on: 'ubuntu-latest'
    steps:
      - name: Deploy ()
        uses: ./.github/workflows/deploy_tool.yml
        with:
          tool: 'conan-iceshard-tools'
          version: '1.0.0'
          user: iceshard
          channel: stable
          platform: ${{ inputs.platform }}

  deploy-tools-dependencies:
    name: Deploy Tools Dependencies
    needs: deploy-conan-iceshard-tools
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 1
      matrix:
        include:
          - library: lua
            version: '5.1.5'
          - library: lua-lpeg
            version: '0.12.0'
          - library: lua-filesystem
            version: '1.8.0'
    steps:
      - name: Deploy (${{ matrix.library }}/${{ matrix.version }})
        uses: ./.github/workflows/deploy_library.yml
        with:
          library: ${{ matrix.library }}
          version: ${{ matrix.version }}
          user: iceshard
          channel: stable
          platform: ${{ inputs.platform }}

  deploy-tools:
    name: Deploy Tools
    needs: deploy-tools-dependencies
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        include:
          - tool: 'ice-build-tools-proxy'
            package: 'ice-build-tools'
            version: '1.9.2'
    steps:
      - name: Deploy (${{ matrix.tool }}/${{ matrix.version }})
        uses: ./.github/workflows/deploy_tool.yml
        with:
          tool: ${{ matrix.tool }}
          version: ${{ matrix.version }}
          user: iceshard
          channel: stable
          platform: ${{ inputs.platform }}
          conan_deploy_package: ${{ matrix.package }}
