name: Deploy Tool (manual)
run-name: Deploy ${{ inputs.tool }}/${{ inputs.version }}@iceshard/${{ inputs.channel }}

on:
  workflow_dispatch:
    inputs:
      tool:
        description: 'The tool recipe to be deployed.'
        required: true
        type: choice
        options:
        - 'conan-iceshard-tools'
        - 'fastbuild-generator'
        - 'fastbuild-installer'
        - 'ice-build-tools-proxy'
        - 'moonscript-installer'
        - 'premake-generator'
        - 'premake-installer'
      version:
        description: 'The library version to be deployed.'
        required: true
        type: string
        default: '1.0.0'
      channel:
        description: 'The channel to which we want the package to be deployed.'
        required: true
        default: 'stable'
        type: choice
        options:
        - stable
        - dev
      platform:
        description: 'The platform that the library should be deployed for.'
        required: true
        type: choice
        default: 'all'
        options:
        - all
        - windows
        - linux
      conan_options:
        description: 'Additional options to be passed to the conan call.'
        required: false
        type: string
        default: ''
      conan_deploy_package:
        description: 'The package to be deployed from the workflow. May be different that the package to be build.'
        required: false
        type: string
        default: ''


jobs:
  deploy-tool:
    name: 'Deploy ${{ github.event.inputs.tool }}'
    uses: ./.github/workflows/deploy_tool_callable.yml
    with:
      tool: ${{ inputs.tool }}
      version: ${{ inputs.version }}
      channel: ${{ inputs.channel }}
      platform: ${{ inputs.platform }}
      conan_options: ${{ inputs.conan_options }}
      conan_deploy_package: ${{ inputs.conan_deploy_package }}
    secrets:
      conan_user: 'iceshard'
      conan_password: ${{ secrets.CONAN_PASSWORD }}
